# Generated by Django 4.1 on 2022-09-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=40)),
                ('subject', models.CharField(max_length=150)),
                ('messages', models.TextField(max_length=500)),
            ],
        ),
    ]
