# Generated by Django 4.1 on 2022-09-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicalfirst', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contact',
        ),
    ]
