# Generated by Django 4.1 on 2022-09-01 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicalfirst', '0003_subscriber_alter_contact_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
