# Generated by Django 4.1 on 2022-09-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicalfirst', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255)),
                ('thumbnail_img', models.ImageField(upload_to='pic')),
                ('desc1', models.TextField()),
                ('post_img2', models.ImageField(upload_to='pic')),
                ('desc2', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='messages',
            field=models.TextField(),
        ),
    ]
