# Generated by Django 4.1 on 2022-09-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicalfirst', '0006_post_alter_contact_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.CharField(default='Technology', max_length=50),
        ),
    ]
