# Generated by Django 4.1 on 2022-09-01 19:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicalfirst', '0010_alter_post_post_key_alter_post_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='desc1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
