# Generated by Django 4.1 on 2022-09-01 19:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicalfirst', '0013_alter_post_desc1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='desc2',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
