# Generated by Django 4.1.1 on 2022-09-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicalfirst', '0014_alter_post_desc2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('comment_name', models.CharField(max_length=30)),
                ('comment_msg', models.CharField(max_length=250)),
                ('comment_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
