# Generated by Django 4.1 on 2022-09-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicalfirst', '0015_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_subtitle',
            field=models.CharField(default='', max_length=255),
        ),
    ]
