# Generated by Django 4.1 on 2022-09-14 09:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicalfirst', '0017_alter_post_post_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_subtitle',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
